version: '3.3'

services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./data/:/data/
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=catedra      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/:/app/data

volumes:
    postgres_volume:
        external: false
