services:
  pgvector:
    container_name: pgvector
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=utdt
      - POSTGRES_USER=utdt
      - POSTGRES_DB=utdt
    ports:
      - 5432:5432
    volumes:
      - pgvector_volume:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis_volume:/data

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_volume/:/app/data

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo4j_volume:/data

  jupyterlab:
    build: .
    volumes:
      - ./notebooks:/notebooks
    ports:
      - 18888:8888
    environment:
      - JUPYTER_TOKEN=utdt
