##Al conectar ahora el host no es "localhost", es el nombre del servicio (postgres)

version: "3"

services:
  dbt:
    container_name: dbt
    build:
      context: ./container_python_dbt
    stdin_open: true # docker run -i
    volumes:
      - ./container_python_dbt/:/usr/src/app/
    ports:
        - "8080:8080"
    
  postgres_e:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./container_db_e/scripts:/docker-entrypoint-initdb.d
      - ./container_db_e/:/container_db_e/
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=catedra
      - POSTGRES_DB=postgres


  postgres_l:
    image: postgres
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./container_db_l/scripts:/docker-entrypoint-initdb.d
      - ./container_db_l/:/container_db_l/
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=catedra
      - POSTGRES_DB=postgres


  jobs:
    build:
      context: ./container_python_etl
    stdin_open: true # docker run -i


    
  
